### PR TITLE
Fix sourceMapCommentRegEx: allow url that have charset

### PR DESCRIPTION
**Pull request by radotzki**
Browserify add "charset:utf-8;" to the url.

### CODE REVIEW

**Comment by duereg** [comment]
@radotzki doesn't work - getting build failures, doesn't seem to match the old style source map strings now. 

Will happily merge once fixed

**Comment by radotzki** [comment]
Fixed.

**Comment by matthewlein** [comment]
This fixed my issue with the latest browserify too. Thanks! Would love to see this merged, I feel weird inside when I edit a node_module.

**Comment by radotzki** [comment]
@matthewlein you can use my fork version until @duereg will accept the pull request.
Just edit your package.json and write:
"grunt-extract-sourcemap": "git://github.com/radotzki/grunt-extract-sourcemap"

**Comment by tirithen** [comment]
:+1:

**Comment by duereg** [comment]
@tirithen @matthewlein @radotzki Merged. I'll publish a new version shortly.

**Comment by duereg** [comment]
@tirithen @matthewlein @radotzki  Published at 0.1.16

**Pull request merged**
